[package]
name = "provwasm-common"
version = "0.3.0-rc1"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = ["Ken Talley <4344285+kwtalley@users.noreply.github.com"]
description = "Common library for ProvWasm internal"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["cryptography::cryptocurrencies", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
ed25519-zebra = { version = "4.1.0", default-features = false, features = [
    "alloc",
] }